// ============================================================================
// WORLD SKELETON — Deterministischer App-Assembler
//
// Das LLM generiert KEINE freie React-App mehr, sondern ein JSON-Spec.
// Diese Funktion baut daraus deterministischen, zuverlässigen React-Code.
//
// Garantiert durch die Skeleton-Architektur:
// ✓ App-Komponente + export default
// ✓ Meoluna.completeModule() bei jedem Modul-Abschluss
// ✓ Meoluna.complete() beim Welt-Abschluss
// ✓ Hub → Modul → Abschluss Navigation
// ✓ "Zurück zum Hub"-Button immer vorhanden
// ✓ Kein HTML-Dokument, kein script src
// ✓ Sokrates-System: Hints + Luna + Auto-speak (Phase 1-4, 2026-02-21)
// ============================================================================

// ── Typen ──────────────────────────────────────────────────────────────────

export interface WorldConfig {
  name: string;
  tagline: string;
  emoji: string;
  primaryColor: string;        // hex, z.B. "#0ea5e9"
  bgGradient: string;          // Tailwind classes, z.B. "from-blue-950 via-blue-900 to-cyan-950"
  cardBg: string;              // Tailwind class, z.B. "bg-blue-900/60"
  accentClass: string;         // Tailwind class für Buttons, z.B. "bg-sky-500 hover:bg-sky-400"
  hubBgUrl?: string;           // Optional: generiertes Hub-Hintergrundbild (Gemini SVG)
  geminiGraphics?: {
    icons: Array<{ id: string; url: string; purpose: string }>;
    illustrations: Array<{ id: string; url: string; purpose: string }>;
    characters: Array<{ id: string; url: string; purpose: string }>;
    backgrounds: Array<{ id: string; url: string; purpose: string }>;
  };
}

export interface MultipleChoiceChallenge {
  type: 'multiple-choice';
  question: string;
  options: string[];
  correct: number;             // Index in options[]
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;   // Denkfrage ("Schau dir die Farben an — was fällt dir auf?")
    level2: string;   // Konkreter Hinweis ("Das gesuchte Tier lebt im Wasser")
    level3: string;   // Fast die Lösung ("Es beginnt mit 'F' und hat Schuppen")
  };
}

export interface TrueFalseChallenge {
  type: 'true-false';
  question: string;
  correct: boolean;
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export interface FillBlankChallenge {
  type: 'fill-blank';
  questionBefore: string;      // Text vor der Lücke
  questionAfter: string;       // Text nach der Lücke
  answer: string;              // Korrekte Antwort (case-insensitive)
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export interface NumberChallenge {
  type: 'number';
  question: string;
  answer: number;
  tolerance: number;
  unit: string;
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export interface SortingChallenge {
  type: 'sorting';
  instruction: string;
  items: string[];             // Shuffled display order
  correct: string[];           // Correct order
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export interface MatchingChallenge {
  type: 'matching';
  instruction: string;
  pairs: Array<{ left: string; right: string }>;
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export interface SimulationChallenge {
  type: 'simulation';
  instruction: string;        // Aufgabentext
  paramLabel: string;         // Label für den Slider
  paramMin: number;
  paramMax: number;
  paramUnit: string;          // z.B. "°C" oder "%"
  targetValue: number;        // Korrekter Wert (innerhalb tolerance)
  tolerance: number;
  sketchDescription: string;  // Was die Simulation visuell zeigt
  xp: number;
  feedbackCorrect: string;
  feedbackWrong: string;
  hints?: {
    level1: string;
    level2: string;
    level3: string;
  };
}

export type Challenge =
  | MultipleChoiceChallenge
  | TrueFalseChallenge
  | FillBlankChallenge
  | NumberChallenge
  | SortingChallenge
  | MatchingChallenge
  | SimulationChallenge;

export interface WorldModule {
  id: number;
  title: string;
  emoji: string;
  description: string;
  challenges: Challenge[];
}

export interface WorldData {
  config: WorldConfig;
  modules: WorldModule[];
}

// ── Assembler ───────────────────────────────────────────────────────────────

/**
 * Baut aus einem WorldData-JSON den vollständigen React-Appcode.
 * Keine LLM-Freiheiten — nur deterministischer Skeleton + injizierte Daten.
 */
export function buildWorldCode(worldData: WorldData): string {
  const dataJson = JSON.stringify(worldData, null, 2);

  return [
    `import { useState, useEffect } from 'react';`,
    `import { motion, AnimatePresence } from 'framer-motion';`,
    `import confetti from 'canvas-confetti';`,
    ``,
    `// ── Welt-Daten (generiert vom LLM, Skeleton bleibt fest) ──`,
    `const WORLD_DATA = ${dataJson};`,
    ``,
    `// ── Hilfsfunktionen ──`,
    `function normalize(s) { return String(s).trim().toLowerCase(); }`,
    `function pickGraphic(list, seed) {`,
    `  if (!Array.isArray(list) || list.length === 0) return null;`,
    `  const i = Math.abs(Number(seed) || 0) % list.length;`,
    `  return list[i] || null;`,
    `}`,
    `function getGraphics() {`,
    `  const g = WORLD_DATA.config?.geminiGraphics || {};`,
    `  return {`,
    `    icons: Array.isArray(g.icons) ? g.icons : [],`,
    `    illustrations: Array.isArray(g.illustrations) ? g.illustrations : [],`,
    `    characters: Array.isArray(g.characters) ? g.characters : [],`,
    `    backgrounds: Array.isArray(g.backgrounds) ? g.backgrounds : [],`,
    `  };`,
    `}`,
    `function getGuideCharacter() {`,
    `  const g = getGraphics();`,
    `  return pickGraphic(g.characters, 0) || pickGraphic(g.illustrations, 0) || pickGraphic(g.icons, 0);`,
    `}`,
    `function getModuleVisual(moduleIndex) {`,
    `  const g = getGraphics();`,
    `  return pickGraphic(g.icons, moduleIndex) || pickGraphic(g.illustrations, moduleIndex) || pickGraphic(g.characters, moduleIndex);`,
    `}`,
    `function getChallengeVisual(moduleIndex, challengeIndex) {`,
    `  const g = getGraphics();`,
    `  const seed = moduleIndex * 10 + challengeIndex;`,
    `  return pickGraphic(g.illustrations, seed) || pickGraphic(g.icons, seed) || pickGraphic(g.characters, seed);`,
    `}`,
    `function WorldGraphic({ asset, alt, className }) {`,
    `  if (!asset?.url) return null;`,
    `  return <img src={asset.url} alt={alt || asset.purpose || 'Grafik'} className={className || ''} loading="eager" decoding="async" />;`,
    `}`,
    ``,
    `// ── Globaler Hint-Callback (Luna kann Hints triggern) ──`,
    `let _advanceHint = null;`,
    ``,
    `// ── Luna Companion ──`,
    `function LunaCompanion({ mood }) {`,
    `  const guide = getGuideCharacter();`,
    `  const moodRing = { happy: 'ring-emerald-300', thinking: 'ring-sky-300', encouraging: 'ring-amber-300' };`,
    `  function handleClick() { if (_advanceHint) _advanceHint(); }`,
    `  return (`,
    `    <motion.button`,
    `      onClick={handleClick}`,
    `      whileHover={{ scale: 1.12 }}`,
    `      whileTap={{ scale: 0.9 }}`,
    `      animate={{ y: [0, -5, 0] }}`,
    `      transition={{ repeat: Infinity, duration: 2.2, ease: 'easeInOut' }}`,
    `      className={'fixed bottom-4 right-4 w-14 h-14 rounded-full flex items-center justify-center shadow-lg z-[9999] border-2 border-white/50 cursor-pointer overflow-hidden bg-slate-900/80 ring-2 ' + (moodRing[mood] || 'ring-white/40')}`,
    `      title="Luna — klick mich für Hilfe!"`,
    `    >`,
    `      <WorldGraphic asset={guide} alt="Luna" className="w-full h-full object-cover" />`,
    `    </motion.button>`,
    `  );`,
    `}`,
    ``,
    `// ── HintBox (wiederverwendbar für alle Challenge-Typen) ──`,
    `function HintBox({ hintLevel, hints, onHelp }) {`,
    `  if (!hints) return null;`,
    `  const key = 'level' + hintLevel;`,
    `  const text = hintLevel > 0 ? hints[key] : null;`,
    `  return (`,
    `    <div className="space-y-2 mt-4">`,
    `      <AnimatePresence>`,
    `        {text && (`,
    `          <motion.div`,
    `            key={hintLevel}`,
    `            initial={{ opacity: 0, y: 8 }}`,
    `            animate={{ opacity: 1, y: 0 }}`,
    `            exit={{ opacity: 0 }}`,
    `            className="p-3 rounded-xl bg-yellow-400/20 border border-yellow-400/40 text-sm text-white"`,
    `          >`,
    `            <span className="mr-2">🌙</span>{text}`,
    `          </motion.div>`,
    `        )}`,
    `      </AnimatePresence>`,
    `      {hintLevel < 3 && (`,
    `        <button`,
    `          onClick={onHelp}`,
    `          className="px-4 py-2 rounded-full text-sm bg-white/20 hover:bg-white/30 text-white transition"`,
    `        >💡 Hilfe?</button>`,
    `      )}`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Feedback-Overlay (nur bei richtiger Antwort) ──`,
    `function FeedbackOverlay({ message, onNext }) {`,
    `  useEffect(() => { if (message) window.Meoluna?.speak?.(message); }, [message]);`,
    `  return (`,
    `    <motion.div`,
    `      initial={{ opacity: 0, scale: 0.8 }}`,
    `      animate={{ opacity: 1, scale: 1 }}`,
    `      exit={{ opacity: 0, scale: 0.8 }}`,
    `      className="fixed inset-0 flex items-center justify-center z-50 p-6"`,
    `    >`,
    `      <div className="rounded-3xl p-8 shadow-2xl max-w-sm w-full text-center bg-green-500">`,
    `        <div className="text-6xl mb-4">✅</div>`,
    `        <p className="text-white text-xl font-bold mb-6">{message}</p>`,
    `        <button`,
    `          onClick={onNext}`,
    `          className="px-8 py-3 bg-white/20 hover:bg-white/30 text-white rounded-xl font-bold text-lg transition-colors"`,
    `        >`,
    `          Weiter →`,
    `        </button>`,
    `      </div>`,
    `    </motion.div>`,
    `  );`,
    `}`,
    ``,
    `// ── Multiple-Choice Challenge ──`,
    `function MultipleChoice({ challenge, onResult, onMoodChange }) {`,
    `  const [done, setDone] = useState(false);`,
    `  const [flashWrong, setFlashWrong] = useState(null);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.question); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function choose(i) {`,
    `    if (done || flashWrong !== null) return;`,
    `    const ok = i === challenge.correct;`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'multiple-choice' });`,
    `      confetti({ particleCount: 60, spread: 70 });`,
    `    } else {`,
    `      setFlashWrong(i);`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `      setTimeout(() => setFlashWrong(null), 800);`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="space-y-4">`,
    `      <p className="text-white text-xl font-semibold text-center mb-6">{challenge.question}</p>`,
    `      <div className="grid gap-3">`,
    `        {challenge.options.map((opt, i) => (`,
    `          <motion.button`,
    `            key={i} whileTap={{ scale: 0.97 }}`,
    `            onClick={() => choose(i)}`,
    `            className={'w-full p-4 rounded-xl text-left font-medium transition-all ' +`,
    `              (done && i === challenge.correct ? 'bg-green-500 text-white' :`,
    `               flashWrong === i ? 'bg-red-500 text-white' :`,
    `               done ? 'bg-white/5 text-white/40' :`,
    `               'bg-white/10 hover:bg-white/20 text-white border border-white/20')}`,
    `          >`,
    `            <span className="font-bold mr-2">{['A','B','C','D'][i]}.</span>{opt}`,
    `          </motion.button>`,
    `        ))}`,
    `      </div>`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── True/False Challenge ──`,
    `function TrueFalse({ challenge, onResult, onMoodChange }) {`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.question); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function choose(val) {`,
    `    if (done) return;`,
    `    const ok = val === challenge.correct;`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'true-false' });`,
    `      confetti({ particleCount: 60, spread: 70 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="space-y-6">`,
    `      <p className="text-white text-xl font-semibold text-center mb-8">{challenge.question}</p>`,
    `      <div className="grid grid-cols-2 gap-4">`,
    `        <motion.button whileTap={{ scale: 0.95 }} onClick={() => choose(true)} disabled={done}`,
    `          className="p-6 rounded-2xl bg-green-600/40 hover:bg-green-600/60 text-white font-bold text-2xl border-2 border-green-500/50 transition-all disabled:opacity-50"`,
    `        >✓ Richtig</motion.button>`,
    `        <motion.button whileTap={{ scale: 0.95 }} onClick={() => choose(false)} disabled={done}`,
    `          className="p-6 rounded-2xl bg-red-600/40 hover:bg-red-600/60 text-white font-bold text-2xl border-2 border-red-500/50 transition-all disabled:opacity-50"`,
    `        >✗ Falsch</motion.button>`,
    `      </div>`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Fill-Blank Challenge ──`,
    `function FillBlank({ challenge, onResult, onMoodChange }) {`,
    `  const [input, setInput] = useState('');`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    `  const [shake, setShake] = useState(false);`,
    ``,
    `  const questionText = challenge.questionBefore + ' [Lücke] ' + challenge.questionAfter;`,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(questionText); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function check() {`,
    `    if (done || !input.trim()) return;`,
    `    const ok = normalize(input) === normalize(challenge.answer);`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'fill-blank' });`,
    `      confetti({ particleCount: 60, spread: 70 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `      setShake(true);`,
    `      setTimeout(() => setShake(false), 500);`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="space-y-6">`,
    `      <p className="text-white text-xl font-semibold text-center">`,
    `        {challenge.questionBefore}`,
    `        <span className="inline-block mx-2 border-b-2 border-white/60 min-w-24 text-center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>`,
    `        {challenge.questionAfter}`,
    `      </p>`,
    `      <motion.div animate={shake ? { x: [-8, 8, -8, 8, 0] } : {}} transition={{ duration: 0.4 }} className="flex gap-3">`,
    `        <input`,
    `          type="text" value={input} onChange={e => setInput(e.target.value)}`,
    `          onKeyDown={e => e.key === 'Enter' && check()}`,
    `          disabled={done}`,
    `          placeholder="Deine Antwort..."`,
    `          className="flex-1 p-4 rounded-xl bg-white/10 border border-white/30 text-white placeholder-white/40 text-lg focus:outline-none focus:border-white/60 disabled:opacity-60"`,
    `        />`,
    `        <motion.button whileTap={{ scale: 0.95 }} onClick={check} disabled={done}`,
    `          className="px-6 py-4 rounded-xl bg-white/20 hover:bg-white/30 text-white font-bold transition-colors disabled:opacity-60"`,
    `        >Prüfen</motion.button>`,
    `      </motion.div>`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect + ' (Richtig: ' + challenge.answer + ')'} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Number Challenge ──`,
    `function NumberChallenge({ challenge, onResult, onMoodChange }) {`,
    `  const [input, setInput] = useState('');`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    `  const [shake, setShake] = useState(false);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.question); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function check() {`,
    `    if (done || !input.trim()) return;`,
    `    const val = parseFloat(input.replace(',', '.'));`,
    `    const ok = !isNaN(val) && Math.abs(val - challenge.answer) <= challenge.tolerance;`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'number' });`,
    `      confetti({ particleCount: 60, spread: 70 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `      setShake(true);`,
    `      setTimeout(() => setShake(false), 500);`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="space-y-6">`,
    `      <p className="text-white text-xl font-semibold text-center">{challenge.question}</p>`,
    `      <motion.div animate={shake ? { x: [-8, 8, -8, 8, 0] } : {}} transition={{ duration: 0.4 }} className="flex gap-3 items-center justify-center">`,
    `        <input`,
    `          type="number" value={input} onChange={e => setInput(e.target.value)}`,
    `          onKeyDown={e => e.key === 'Enter' && check()}`,
    `          disabled={done}`,
    `          placeholder="0"`,
    `          className="w-40 p-4 rounded-xl bg-white/10 border border-white/30 text-white text-xl text-center focus:outline-none focus:border-white/60 disabled:opacity-60"`,
    `        />`,
    `        <span className="text-white/70 text-lg">{challenge.unit}</span>`,
    `        <motion.button whileTap={{ scale: 0.95 }} onClick={check} disabled={done}`,
    `          className="px-6 py-4 rounded-xl bg-white/20 hover:bg-white/30 text-white font-bold transition-colors disabled:opacity-60"`,
    `        >Prüfen</motion.button>`,
    `      </motion.div>`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect + ' (Richtig: ' + challenge.answer + ' ' + challenge.unit + ')'} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Sorting Challenge ──`,
    `function SortingChallenge({ challenge, onResult, onMoodChange }) {`,
    `  const [items, setItems] = useState(() => [...challenge.items]);`,
    `  const [selectedIdx, setSelectedIdx] = useState(null);`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.instruction); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function clickItem(i) {`,
    `    if (done) return;`,
    `    if (selectedIdx === null) { setSelectedIdx(i); return; }`,
    `    const next = [...items];`,
    `    [next[selectedIdx], next[i]] = [next[i], next[selectedIdx]];`,
    `    setItems(next); setSelectedIdx(null);`,
    `  }`,
    ``,
    `  function check() {`,
    `    const ok = items.every((item, i) => item === challenge.correct[i]);`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'sorting' });`,
    `      confetti({ particleCount: 80, spread: 80 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="space-y-4">`,
    `      <p className="text-white text-lg font-semibold text-center mb-4">{challenge.instruction}</p>`,
    `      <p className="text-white/60 text-sm text-center">Klicke zwei Elemente zum Tauschen</p>`,
    `      <div className="space-y-2">`,
    `        {items.map((item, i) => (`,
    `          <motion.button key={i} whileTap={{ scale: 0.97 }} onClick={() => clickItem(i)} disabled={done}`,
    `            className={'w-full p-3 rounded-xl text-white font-medium text-left flex items-center gap-3 transition-all ' +`,
    `              (selectedIdx === i ? 'bg-yellow-500/60 border-2 border-yellow-400' : 'bg-white/10 hover:bg-white/20 border border-white/20')}`,
    `          >`,
    `            <span className="w-7 h-7 rounded-full bg-white/20 flex items-center justify-center text-sm font-bold">{i + 1}</span>`,
    `            {item}`,
    `          </motion.button>`,
    `        ))}`,
    `      </div>`,
    `      {!done && <motion.button whileTap={{ scale: 0.97 }} onClick={check}`,
    `        className="w-full py-3 rounded-xl bg-white/20 hover:bg-white/30 text-white font-bold transition-colors"`,
    `      >Reihenfolge prüfen ✓</motion.button>}`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Matching Challenge ──`,
    `function MatchingChallenge({ challenge, onResult, onMoodChange }) {`,
    `  const [selectedLeft, setSelectedLeft] = useState(null);`,
    `  const [matches, setMatches] = useState({});`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    `  const rights = challenge.pairs.map(p => p.right);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.instruction); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function clickLeft(i) { if (done) return; setSelectedLeft(i); }`,
    `  function clickRight(i) {`,
    `    if (done || selectedLeft === null) return;`,
    `    setMatches(m => ({ ...m, [selectedLeft]: i }));`,
    `    setSelectedLeft(null);`,
    `  }`,
    ``,
    `  function check() {`,
    `    const ok = challenge.pairs.every((_, i) => matches[i] === i);`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'matching' });`,
    `      confetti({ particleCount: 80, spread: 80 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `    }`,
    `  }`,
    ``,
    `  function reset() { setMatches({}); setSelectedLeft(null); }`,
    `  const allMatched = Object.keys(matches).length === challenge.pairs.length;`,
    ``,
    `  return (`,
    `    <div className="space-y-4">`,
    `      <p className="text-white text-lg font-semibold text-center mb-2">{challenge.instruction}</p>`,
    `      <div className="grid grid-cols-2 gap-3">`,
    `        <div className="space-y-2">`,
    `          {challenge.pairs.map((p, i) => (`,
    `            <motion.button key={i} whileTap={{ scale: 0.97 }} onClick={() => clickLeft(i)} disabled={done}`,
    `              className={'w-full p-3 rounded-xl text-white text-sm font-medium transition-all ' +`,
    `                (selectedLeft === i ? 'bg-yellow-500/70 border-2 border-yellow-300' :`,
    `                 matches[i] !== undefined ? 'bg-green-500/40 border border-green-400/50' :`,
    `                 'bg-white/10 hover:bg-white/20 border border-white/20')}`,
    `            >{p.left}</motion.button>`,
    `          ))}`,
    `        </div>`,
    `        <div className="space-y-2">`,
    `          {rights.map((r, i) => (`,
    `            <motion.button key={i} whileTap={{ scale: 0.97 }} onClick={() => clickRight(i)} disabled={done}`,
    `              className={'w-full p-3 rounded-xl text-white text-sm font-medium transition-all ' +`,
    `                (Object.values(matches).includes(i) ? 'bg-blue-500/40 border border-blue-400/50' :`,
    `                 'bg-white/10 hover:bg-white/20 border border-white/20')}`,
    `            >{r}</motion.button>`,
    `          ))}`,
    `        </div>`,
    `      </div>`,
    `      <div className="flex gap-2">`,
    `        {allMatched && !done && <motion.button whileTap={{ scale: 0.97 }} onClick={check}`,
    `          className="flex-1 py-3 rounded-xl bg-white/20 hover:bg-white/30 text-white font-bold transition-colors"`,
    `        >Zuordnung prüfen ✓</motion.button>}`,
    `        {!done && <motion.button whileTap={{ scale: 0.97 }} onClick={reset}`,
    `          className="px-4 py-3 rounded-xl bg-white/10 hover:bg-white/20 text-white/70 text-sm transition-colors"`,
    `        >Zurücksetzen</motion.button>}`,
    `      </div>`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Simulation Challenge ──`,
    `function SimulationChallenge({ challenge, onResult, onMoodChange }) {`,
    `  const [value, setValue] = useState(() => Math.round((challenge.paramMin + challenge.paramMax) / 2));`,
    `  const [done, setDone] = useState(false);`,
    `  const [wrongAttempts, setWrongAttempts] = useState(0);`,
    `  const [hintLevel, setHintLevel] = useState(0);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => { window.Meoluna?.speak?.(challenge.instruction); }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  useEffect(() => {`,
    `    _advanceHint = advanceHint;`,
    `    return () => { _advanceHint = null; };`,
    `  });`,
    ``,
    `  function advanceHint() {`,
    `    const next = Math.min(3, hintLevel + 1);`,
    `    setHintLevel(next);`,
    `    if (challenge.hints) {`,
    `      const hint = challenge.hints['level' + next];`,
    `      if (hint) window.Meoluna?.speak?.(hint);`,
    `    }`,
    `  }`,
    ``,
    `  function check() {`,
    `    if (done) return;`,
    `    const ok = Math.abs(value - challenge.targetValue) <= challenge.tolerance;`,
    `    if (ok) {`,
    `      setDone(true);`,
    `      if (onMoodChange) onMoodChange('happy');`,
    `      Meoluna.reportScore(challenge.xp, { action: 'correct', type: 'simulation' });`,
    `      confetti({ particleCount: 80, spread: 80 });`,
    `    } else {`,
    `      const next = wrongAttempts + 1;`,
    `      setWrongAttempts(next);`,
    `      if (onMoodChange) onMoodChange(next >= 3 ? 'thinking' : 'encouraging');`,
    `      window.Meoluna?.speak?.(challenge.feedbackWrong);`,
    `      if (next >= 6 && hintLevel < 3) setHintLevel(3);`,
    `      else if (next >= 4 && hintLevel < 2) setHintLevel(2);`,
    `      else if (next >= 2 && hintLevel < 1) setHintLevel(1);`,
    `    }`,
    `  }`,
    ``,
    `  const pct = (value - challenge.paramMin) / (challenge.paramMax - challenge.paramMin);`,
    `  const hue = Math.round((1 - pct) * 220);`,
    ``,
    `  return (`,
    `    <div className="space-y-6">`,
    `      <p className="text-white text-xl font-semibold text-center">{challenge.instruction}</p>`,
    `      <div className="flex flex-col items-center gap-5 p-6 rounded-2xl bg-black/30">`,
    `        <div`,
    `          className="w-36 h-36 rounded-full flex items-center justify-center text-3xl font-bold text-white shadow-lg transition-all duration-200"`,
    `          style={{ background: 'hsl(' + hue + ', 65%, 45%)' }}`,
    `        >{value}{challenge.paramUnit}</div>`,
    `        <p className="text-white/60 text-sm">{challenge.paramLabel}</p>`,
    `        <input`,
    `          type="range"`,
    `          min={challenge.paramMin} max={challenge.paramMax} value={value}`,
    `          onChange={e => setValue(Number(e.target.value))}`,
    `          disabled={done}`,
    `          className="w-full max-w-xs h-3 rounded-lg cursor-pointer"`,
    `          style={{ accentColor: 'hsl(' + hue + ', 65%, 55%)' }}`,
    `        />`,
    `        <div className="flex justify-between w-full max-w-xs text-white/40 text-xs">`,
    `          <span>{challenge.paramMin}{challenge.paramUnit}</span>`,
    `          <span>{challenge.paramMax}{challenge.paramUnit}</span>`,
    `        </div>`,
    `      </div>`,
    `      {!done && (`,
    `        <motion.button whileTap={{ scale: 0.97 }} onClick={check}`,
    `          className="w-full py-3 rounded-xl bg-white/20 hover:bg-white/30 text-white font-bold text-lg transition-colors"`,
    `        >Bestätigen ✓</motion.button>`,
    `      )}`,
    `      <HintBox hintLevel={hintLevel} hints={challenge.hints} onHelp={advanceHint} />`,
    `      <AnimatePresence>`,
    `        {done && <FeedbackOverlay message={challenge.feedbackCorrect} onNext={() => onResult(true)} />}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Challenge Router ──`,
    `function ChallengeView({ challenge, onResult, onMoodChange }) {`,
    `  const t = challenge.type;`,
    `  if (t === 'multiple-choice') return <MultipleChoice challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'true-false') return <TrueFalse challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'fill-blank') return <FillBlank challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'number') return <NumberChallenge challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'sorting') return <SortingChallenge challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'matching') return <MatchingChallenge challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  if (t === 'simulation') return <SimulationChallenge challenge={challenge} onResult={onResult} onMoodChange={onMoodChange} />;`,
    `  return <p className="text-red-400">Unbekannter Challenge-Typ: {challenge.type}</p>;`,
    `}`,
    ``,
    `// ── Modul-Screen ──`,
    `function ModuleScreen({ mod, moduleIndex, onComplete, onBack }) {`,
    `  const [challengeIndex, setChallengeIndex] = useState(0);`,
    `  const [score, setScore] = useState(0);`,
    `  const [done, setDone] = useState(false);`,
    `  const [lunaMood, setLunaMood] = useState('thinking');`,
    `  const cfg = WORLD_DATA.config;`,
    ``,
    `  function handleResult() {`,
    `    setScore(s => s + (mod.challenges[challengeIndex]?.xp || 10));`,
    `    setLunaMood('happy');`,
    `    const next = challengeIndex + 1;`,
    `    if (next >= mod.challenges.length) {`,
    `      setTimeout(() => {`,
    `        window.Meoluna?.speak?.('Super! Du hast ' + mod.title + ' abgeschlossen!');`,
    `        setDone(true);`,
    `      }, 800);`,
    `    } else {`,
    `      setTimeout(() => {`,
    `        setLunaMood('thinking');`,
    `        setChallengeIndex(next);`,
    `      }, 600);`,
    `    }`,
    `  }`,
    ``,
    `  if (done) return (`,
    `    <div className="min-h-screen flex flex-col items-center justify-center p-6 text-center">`,
    `      <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="space-y-6">`,
    `        <div className="mx-auto w-40 h-40 rounded-3xl bg-white/5 border border-white/10 p-2 overflow-hidden">`,
    `          <WorldGraphic asset={getModuleVisual(moduleIndex)} alt={mod.title} className="w-full h-full object-contain" />`,
    `        </div>`,
    `        <h2 className="text-white text-3xl font-bold">{mod.title} abgeschlossen!</h2>`,
    `        <p className="text-white/70 text-xl">+{score} Punkte</p>`,
    `        <motion.button whileTap={{ scale: 0.97 }} onClick={() => onComplete(score)}`,
    `          className={'px-10 py-4 rounded-2xl text-white font-bold text-xl ' + cfg.accentClass}`,
    `        >Weiter zum Hub →</motion.button>`,
    `      </motion.div>`,
    `      <LunaCompanion mood="happy" />`,
    `    </div>`,
    `  );`,
    ``,
    `  const challenge = mod.challenges[challengeIndex];`,
    `  const moduleVisual = getModuleVisual(moduleIndex);`,
    `  const challengeVisual = getChallengeVisual(moduleIndex, challengeIndex);`,
    `  const progress = (challengeIndex / mod.challenges.length) * 100;`,
    ``,
    `  return (`,
    `    <div className="min-h-screen flex flex-col p-4 bg-cover bg-center" style={cfg.hubBgUrl ? { backgroundImage: 'url(' + cfg.hubBgUrl + ')' } : undefined}>`,
    `      <div className="flex items-center gap-3 mb-6">`,
    `        <button onClick={onBack} className="text-white/70 hover:text-white transition-colors text-sm px-3 py-2 rounded-lg bg-white/10 hover:bg-white/20">`,
    `          ← Hub`,
    `        </button>`,
    `        <div className="flex-1 h-2 bg-white/20 rounded-full overflow-hidden">`,
    `          <motion.div animate={{ width: progress + '%' }} className="h-full bg-white rounded-full" />`,
    `        </div>`,
    `        <span className="text-white/70 text-sm">{challengeIndex + 1}/{mod.challenges.length}</span>`,
    `      </div>`,
    `      <div className="flex-1 flex flex-col justify-center max-w-2xl w-full mx-auto">`,
    `        <div className="mb-6 text-center">`,
    `          <div className="mx-auto mb-3 w-28 h-28 rounded-2xl bg-white/5 border border-white/10 p-2 overflow-hidden">`,
    `            <WorldGraphic asset={moduleVisual} alt={mod.title} className="w-full h-full object-contain" />`,
    `          </div>`,
    `          <h2 className="text-white font-bold text-xl mt-1">{mod.title}</h2>`,
    `        </div>`,
    `        <div className={'rounded-2xl p-6 ' + cfg.cardBg}>`,
    `          {challengeVisual && (`,
    `            <div className="mb-5 rounded-xl border border-white/10 bg-black/20 p-2">`,
    `              <WorldGraphic asset={challengeVisual} alt={challengeVisual.purpose || mod.title} className="w-full max-h-48 object-contain mx-auto" />`,
    `            </div>`,
    `          )}`,
    `          <AnimatePresence mode="wait">`,
    `            <motion.div key={challengeIndex}`,
    `              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }}`,
    `            >`,
    `              <ChallengeView challenge={challenge} onResult={handleResult} onMoodChange={setLunaMood} />`,
    `            </motion.div>`,
    `          </AnimatePresence>`,
    `        </div>`,
    `      </div>`,
    `      <LunaCompanion mood={lunaMood} />`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Hub-Screen ──`,
    `function HubScreen({ completedModules, totalScore, onSelectModule }) {`,
    `  const cfg = WORLD_DATA.config;`,
    `  const allDone = completedModules.length >= WORLD_DATA.modules.length;`,
    `  const guide = getGuideCharacter();`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => {`,
    `      window.Meoluna?.speak?.('Willkommen in ' + cfg.name + '! ' + cfg.tagline);`,
    `    }, 800);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  return (`,
    `    <div`,
    `      className="min-h-screen flex flex-col items-center p-6 relative overflow-hidden bg-gradient-to-br"`,
    `      style={cfg.hubBgUrl ? { backgroundImage: 'url(' + cfg.hubBgUrl + ')', backgroundSize: 'cover', backgroundPosition: 'center' } : undefined}`,
    `    >`,
    `      {cfg.hubBgUrl && <div className="absolute inset-0 bg-black/55 pointer-events-none" />}`,
    `      <div className="relative z-10 max-w-2xl w-full space-y-8 pt-8">`,
    `        <div className="text-center space-y-2">`,
    `          {guide && (`,
    `            <div className="mx-auto mb-3 w-40 h-40 rounded-3xl bg-white/5 border border-white/10 p-3 overflow-hidden">`,
    `              <WorldGraphic asset={guide} alt="Welt-Guide" className="w-full h-full object-contain" />`,
    `            </div>`,
    `          )}`,
    `          <h1 className="text-white text-3xl font-bold">{cfg.name}</h1>`,
    `          <p className="text-white/70">{cfg.tagline}</p>`,
    `          {totalScore > 0 && <p className="text-white/50 text-sm">{totalScore} Punkte gesammelt</p>}`,
    `        </div>`,
    `        {allDone && (`,
    `          <div className="text-center p-6 rounded-2xl bg-yellow-500/20 border border-yellow-500/40">`,
    `            <div className="text-4xl mb-2">🏆</div>`,
    `            <p className="text-yellow-300 font-bold text-xl">Alle Module abgeschlossen!</p>`,
    `          </div>`,
    `        )}`,
    `        <div className="grid gap-4">`,
    `          {WORLD_DATA.modules.map((mod, i) => {`,
    `            const done = completedModules.includes(i);`,
    `            const moduleVisual = getModuleVisual(i);`,
    `            return (`,
    `              <motion.button key={i} whileTap={{ scale: 0.98 }} onClick={() => onSelectModule(i)}`,
    `                className={'w-full p-5 rounded-2xl text-left flex items-center gap-4 transition-all ' + cfg.cardBg + ' border ' + (done ? 'border-green-500/50' : 'border-white/10 hover:border-white/30')}`,
    `              >`,
    `                <div className="w-16 h-16 rounded-xl bg-white/5 border border-white/10 p-2 overflow-hidden shrink-0">`,
    `                  <WorldGraphic asset={moduleVisual} alt={mod.title} className="w-full h-full object-contain" />`,
    `                </div>`,
    `                <div className="flex-1">`,
    `                  <div className="text-white font-bold text-lg">{mod.title}</div>`,
    `                  <div className="text-white/60 text-sm mt-0.5">{mod.description}</div>`,
    `                  <div className="text-white/40 text-xs mt-1">{mod.challenges.length} Aufgaben</div>`,
    `                </div>`,
    `                <div className="text-2xl">{done ? '✅' : '▶'}</div>`,
    `              </motion.button>`,
    `            );`,
    `          })}`,
    `        </div>`,
    `      </div>`,
    `      <LunaCompanion mood="thinking" />`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── Completion-Screen ──`,
    `function CompletionScreen({ totalScore, onRestart }) {`,
    `  const cfg = WORLD_DATA.config;`,
    `  const hero = getGuideCharacter() || pickGraphic(getGraphics().illustrations, 1) || pickGraphic(getGraphics().icons, 1);`,
    ``,
    `  useEffect(() => {`,
    `    const t = setTimeout(() => {`,
    `      window.Meoluna?.speak?.('Herzlichen Glückwunsch! Du hast alle Module abgeschlossen! ' + totalScore + ' Punkte!');`,
    `    }, 600);`,
    `    return () => clearTimeout(t);`,
    `  }, []);`,
    ``,
    `  return (`,
    `    <div className="min-h-screen flex flex-col items-center justify-center p-6 text-center">`,
    `      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6 max-w-md w-full">`,
    `        {hero && (`,
    `          <div className="mx-auto w-44 h-44 rounded-3xl bg-white/5 border border-white/10 p-3 overflow-hidden">`,
    `            <WorldGraphic asset={hero} alt="Erfolgsillustration" className="w-full h-full object-contain" />`,
    `          </div>`,
    `        )}`,
    `        <h1 className="text-white text-4xl font-bold">{cfg.name}</h1>`,
    `        <p className="text-white/70 text-xl">Alle Module abgeschlossen!</p>`,
    `        <div className="text-6xl font-bold" style={{ color: cfg.primaryColor }}>{totalScore}</div>`,
    `        <p className="text-white/50 text-lg">Punkte gesammelt</p>`,
    `        <div className="flex flex-col gap-3 pt-4">`,
    `          <motion.button whileTap={{ scale: 0.97 }} onClick={onRestart}`,
    `            className={'w-full py-4 rounded-2xl text-white font-bold text-lg ' + cfg.accentClass}`,
    `          >🔄 Nochmal spielen</motion.button>`,
    `        </div>`,
    `      </motion.div>`,
    `      <LunaCompanion mood="happy" />`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `// ── App (Haupt-Komponente) ──`,
    `export default function App() {`,
    `  const cfg = WORLD_DATA.config;`,
    `  const [view, setView] = useState('hub');`,
    `  const [currentModuleIndex, setCurrentModuleIndex] = useState(0);`,
    `  const [completedModules, setCompletedModules] = useState([]);`,
    `  const [totalScore, setTotalScore] = useState(0);`,
    ``,
    `  function selectModule(i) {`,
    `    setCurrentModuleIndex(i);`,
    `    setView('module');`,
    `  }`,
    ``,
    `  function handleModuleComplete(score) {`,
    `    Meoluna.completeModule(currentModuleIndex);`,
    `    const newCompleted = completedModules.includes(currentModuleIndex)`,
    `      ? completedModules`,
    `      : [...completedModules, currentModuleIndex];`,
    `    const newScore = totalScore + score;`,
    `    setCompletedModules(newCompleted);`,
    `    setTotalScore(newScore);`,
    `    if (newCompleted.length >= WORLD_DATA.modules.length) {`,
    `      Meoluna.complete(newScore);`,
    `      setView('completion');`,
    `    } else {`,
    `      setView('hub');`,
    `    }`,
    `  }`,
    ``,
    `  function handleRestart() {`,
    `    setView('hub');`,
    `    setCompletedModules([]);`,
    `    setTotalScore(0);`,
    `    setCurrentModuleIndex(0);`,
    `  }`,
    ``,
    `  return (`,
    `    <div className={'min-h-screen bg-gradient-to-br ' + cfg.bgGradient}>`,
    `      <style>{'svg { max-width: 100%; height: auto; display: block; } img { max-width: 100%; height: auto; }'}</style>`,
    `      <AnimatePresence mode="wait">`,
    `        {view === 'hub' && (`,
    `          <motion.div key="hub" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>`,
    `            <HubScreen completedModules={completedModules} totalScore={totalScore} onSelectModule={selectModule} />`,
    `          </motion.div>`,
    `        )}`,
    `        {view === 'module' && (`,
    `          <motion.div key="module" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>`,
    `            <ModuleScreen`,
    `              mod={WORLD_DATA.modules[currentModuleIndex]}`,
    `              moduleIndex={currentModuleIndex}`,
    `              onComplete={handleModuleComplete}`,
    `              onBack={() => setView('hub')}`,
    `            />`,
    `          </motion.div>`,
    `        )}`,
    `        {view === 'completion' && (`,
    `          <motion.div key="completion" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>`,
    `            <CompletionScreen totalScore={totalScore} onRestart={handleRestart} />`,
    `          </motion.div>`,
    `        )}`,
    `      </AnimatePresence>`,
    `    </div>`,
    `  );`,
    `}`,
  ].join('\n');
}
