import type { MovementEngineSpec } from "./movementSpaceTypes";
import { validateMovementEngineSpec } from "./movementSpaceValidator";

export function buildMovementSpaceWorldCode(spec: MovementEngineSpec): string {
  const validation = validateMovementEngineSpec(spec);
  if (!validation.passed) {
    throw new Error(`Invalid movement-space spec: ${validation.violations.join(" | ")}`);
  }

  const dataJson = JSON.stringify(spec, null, 2);

  return [
    `import { useMemo, useState } from 'react';`,
    `import { motion, AnimatePresence } from 'framer-motion';`,
    `import confetti from 'canvas-confetti';`,
    ``,
    `const SPEC = ${dataJson};`,
    ``,
    `function is2D(position) {`,
    `  return typeof position === 'object' && position !== null;`,
    `}`,
    ``,
    `function addPositions(start, moves) {`,
    `  if (is2D(start)) {`,
    `    return moves.reduce((sum, move) => ({ x: sum.x + move.value.x, y: sum.y + move.value.y }), start);`,
    `  }`,
    `  return moves.reduce((sum, move) => sum + move.value, start);`,
    `}`,
    ``,
    `function samePosition(a, b) {`,
    `  if (is2D(a) || is2D(b)) return is2D(a) && is2D(b) && a.x === b.x && a.y === b.y;`,
    `  return a === b;`,
    `}`,
    ``,
    `function positionLabel(position, unitLabel) {`,
    `  if (is2D(position)) return '(' + position.x + ', ' + position.y + ') ' + unitLabel;`,
    `  return position + ' ' + unitLabel;`,
    `}`,
    ``,
    `function axisPercent(value, coordinateSystem) {`,
    `  const pct = ((value - coordinateSystem.min) / (coordinateSystem.max - coordinateSystem.min)) * 100;`,
    `  return Math.max(4, Math.min(96, pct));`,
    `}`,
    ``,
    `function getRoomMeta(roomId) {`,
    `  return SPEC.world.rooms.find((room) => room.id === roomId) || {};`,
    `}`,
    ``,
    `function GuidePanel({ room, message }) {`,
    `  return (`,
    `    <div className="rounded-2xl border border-white/10 bg-white/10 p-4 sm:p-5 shadow-2xl backdrop-blur">`,
    `      <div className="flex items-start gap-3">`,
    `        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/15 text-2xl">✦</div>`,
    `        <div>`,
    `          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-white/60">{SPEC.world.guide.name}</p>`,
    `          <p className="mt-1 text-lg font-bold text-white">{message || room.objective}</p>`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function AxisScene({ room, position, targetPreview }) {`,
    `  const coordinateSystem = SPEC.coordinateSystem;`,
    `  const horizontal = coordinateSystem.dimensions !== '1d-vertical';`,
    `  const numericPosition = typeof position === 'number' ? position : position.x;`,
    `  const numericTarget = typeof room.targetPosition === 'number' ? room.targetPosition : room.targetPosition.x;`,
    `  const markerStyle = horizontal`,
    `    ? { left: axisPercent(numericPosition, coordinateSystem) + '%', top: '50%' }`,
    `    : { left: '50%', bottom: axisPercent(numericPosition, coordinateSystem) + '%' };`,
    `  const targetStyle = horizontal`,
    `    ? { left: axisPercent(numericTarget, coordinateSystem) + '%', top: '50%' }`,
    `    : { left: '50%', bottom: axisPercent(numericTarget, coordinateSystem) + '%' };`,
    `  return (`,
    `    <div className="relative h-64 overflow-hidden rounded-3xl border border-white/10 bg-black/30 p-6 shadow-2xl">`,
    `      <div className="absolute inset-0 opacity-30" style={{ background: 'radial-gradient(circle at 30% 20%, ' + SPEC.world.visualStyle.palette[2] + '55, transparent 30%), radial-gradient(circle at 75% 70%, ' + SPEC.world.visualStyle.palette[3] + '44, transparent 28%)' }} />`,
    `      <div className={horizontal ? 'absolute left-8 right-8 top-1/2 h-1 rounded-full bg-white/25' : 'absolute bottom-8 top-8 left-1/2 w-1 rounded-full bg-white/25'} />`,
    `      <div className="absolute left-8 bottom-5 text-xs font-semibold text-white/55">{coordinateSystem.negativeDirectionLabel}</div>`,
    `      <div className="absolute right-8 bottom-5 text-xs font-semibold text-white/55">{coordinateSystem.positiveDirectionLabel}</div>`,
    `      <motion.div`,
    `        className="absolute z-20 flex h-16 min-w-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-2xl bg-amber-300 px-3 text-center text-sm font-black text-slate-950 shadow-lg shadow-amber-300/30"`,
    `        animate={markerStyle}`,
    `        transition={{ type: 'spring', stiffness: 120, damping: 18 }}`,
    `      >`,
    `        {positionLabel(position, coordinateSystem.unitLabel)}`,
    `      </motion.div>`,
    `      <div className="absolute z-10 h-12 w-12 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-emerald-300/80 bg-emerald-300/20 shadow-lg shadow-emerald-300/30" style={targetStyle} />`,
    `      {targetPreview !== null && (`,
    `        <div className="absolute right-5 top-5 rounded-xl bg-white/10 px-3 py-2 text-sm text-white/75">Zielversuch: {positionLabel(targetPreview, coordinateSystem.unitLabel)}</div>`,
    `      )}`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function RoomScene({ room, onBack, onComplete }) {`,
    `  const roomMeta = getRoomMeta(room.roomId);`,
    `  const [position, setPosition] = useState(room.startPosition);`,
    `  const [stepIndex, setStepIndex] = useState(0);`,
    `  const [targetGuess, setTargetGuess] = useState(typeof room.targetPosition === 'number' ? room.startPosition : room.targetPosition);`,
    `  const [feedback, setFeedback] = useState(null);`,
    `  const currentMove = room.moves[stepIndex];`,
    `  const targetPreview = room.interaction === 'drag-marker' ? targetGuess : null;`,
    ``,
    `  function completeRoom(message) {`,
    `    setFeedback({ type: 'success', message });`,
    `    Meoluna.reportScore(25, { action: 'movement-room-complete', roomId: room.roomId });`,
    `    Meoluna.completeModule(room.roomId, 25);`,
    `    confetti({ particleCount: 90, spread: 70, origin: { y: 0.65 } });`,
    `    setTimeout(onComplete, 1200);`,
    `  }`,
    ``,
    `  function applyMove() {`,
    `    if (!currentMove) return;`,
    `    const nextPosition = addPositions(position, [currentMove]);`,
    `    setPosition(nextPosition);`,
    `    setStepIndex((value) => value + 1);`,
    `    if (stepIndex + 1 >= room.moves.length) {`,
    `      const expected = addPositions(room.startPosition, room.moves);`,
    `      if (samePosition(expected, room.targetPosition)) {`,
    `        completeRoom(room.feedback.correct);`,
    `      }`,
    `    } else {`,
    `      setFeedback({ type: 'progress', message: currentMove.meaning + ': ' + currentMove.label });`,
    `    }`,
    `  }`,
    ``,
    `  function checkDragTarget() {`,
    `    if (samePosition(Number(targetGuess), room.targetPosition)) {`,
    `      setPosition(room.targetPosition);`,
    `      completeRoom(room.feedback.correct);`,
    `      return;`,
    `    }`,
    `    const target = typeof room.targetPosition === 'number' ? room.targetPosition : room.targetPosition.x;`,
    `    const guess = Number(targetGuess);`,
    `    const start = typeof room.startPosition === 'number' ? room.startPosition : room.startPosition.x;`,
    `    const correctDirection = Math.sign(target - start) === Math.sign(guess - start);`,
    `    setFeedback({ type: 'error', message: correctDirection ? room.feedback.wrongDistance : room.feedback.wrongDirection });`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="min-h-screen p-4 text-white sm:p-8" style={{ background: 'linear-gradient(135deg, ' + SPEC.world.visualStyle.palette[0] + ', ' + SPEC.world.visualStyle.palette[1] + ')' }}>`,
    `      <div className="mx-auto flex max-w-6xl flex-col gap-5">`,
    `        <div className="flex items-center justify-between gap-3">`,
    `          <button onClick={onBack} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold text-white/80 hover:bg-white/15">← Karte</button>`,
    `          <div className="rounded-xl bg-white/10 px-4 py-2 text-sm text-white/70">{roomMeta.title || room.roomId}</div>`,
    `        </div>`,
    `        <GuidePanel room={room} message={feedback?.message} />`,
    `        <AxisScene room={room} position={position} targetPreview={targetPreview} />`,
    `        <div className="grid gap-4 lg:grid-cols-[1fr_auto]">`,
    `          <div className="rounded-2xl border border-white/10 bg-white/10 p-5">`,
    `            <p className="text-sm uppercase tracking-[0.18em] text-white/50">Aha-Ziel</p>`,
    `            <h2 className="mt-1 text-2xl font-black">{SPEC.concept.successInsight}</h2>`,
    `            <p className="mt-2 text-white/70">{room.explanationAfterSuccess}</p>`,
    `          </div>`,
    `          {room.interaction === 'drag-marker' ? (`,
    `            <div className="rounded-2xl border border-white/10 bg-white/10 p-5">`,
    `              <label className="text-sm font-bold text-white/70">Setze den Zielmarker</label>`,
    `              <input className="mt-4 w-full accent-amber-300" type="range" min={SPEC.coordinateSystem.min} max={SPEC.coordinateSystem.max} value={targetGuess} onChange={(event) => setTargetGuess(Number(event.target.value))} />`,
    `              <button onClick={checkDragTarget} className="mt-4 w-full rounded-xl bg-amber-300 px-6 py-4 font-black text-slate-950 hover:bg-amber-200">Ziel prüfen</button>`,
    `            </div>`,
    `          ) : (`,
    `            <button onClick={applyMove} disabled={!currentMove} className="rounded-2xl bg-amber-300 px-8 py-5 text-xl font-black text-slate-950 shadow-lg shadow-amber-300/20 hover:bg-amber-200 disabled:opacity-40">`,
    `              {currentMove ? currentMove.label : 'Raum geschafft'}`,
    `            </button>`,
    `          )}`,
    `        </div>`,
    `        {feedback?.type === 'error' && (`,
    `          <div className="rounded-2xl border border-red-300/30 bg-red-500/20 p-4 text-red-50">{feedback.message}</div>`,
    `        )}`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function Hub({ completedRooms, onStart }) {`,
    `  return (`,
    `    <div className="min-h-screen p-4 text-white sm:p-8" style={{ background: 'linear-gradient(135deg, ' + SPEC.world.visualStyle.palette[0] + ', ' + SPEC.world.visualStyle.palette[1] + ')' }}>`,
    `      <div className="mx-auto max-w-6xl">`,
    `        <div className="mb-8 rounded-3xl border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur">`,
    `          <p className="text-sm uppercase tracking-[0.2em] text-white/55">Meoluna Movement Engine</p>`,
    `          <h1 className="mt-2 text-4xl font-black sm:text-6xl">{SPEC.world.worldName}</h1>`,
    `          <p className="mt-3 max-w-3xl text-lg text-white/75">{SPEC.world.setting}</p>`,
    `        </div>`,
    `        <div className="grid gap-4 md:grid-cols-2">`,
    `          {SPEC.rooms.map((room, index) => {`,
    `            const meta = getRoomMeta(room.roomId);`,
    `            const done = completedRooms.includes(room.roomId);`,
    `            return (`,
    `              <button key={room.roomId} onClick={() => onStart(index)} className="group rounded-3xl border border-white/10 bg-white/10 p-5 text-left shadow-xl transition hover:-translate-y-1 hover:bg-white/15">`,
    `                <div className="flex items-start justify-between gap-4">`,
    `                  <div>`,
    `                    <p className="text-sm font-bold uppercase tracking-[0.16em] text-white/50">Raum {index + 1}</p>`,
    `                    <h2 className="mt-1 text-2xl font-black">{meta.title || room.objective}</h2>`,
    `                    <p className="mt-2 text-white/70">{meta.scene || room.objective}</p>`,
    `                  </div>`,
    `                  <div className="rounded-2xl bg-white/10 px-3 py-2 text-sm font-black">{done ? '✓' : '→'}</div>`,
    `                </div>`,
    `              </button>`,
    `            );`,
    `          })}`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export default function App() {`,
    `  const [activeRoomIndex, setActiveRoomIndex] = useState(null);`,
    `  const [completedRooms, setCompletedRooms] = useState([]);`,
    `  function completeActiveRoom() {`,
    `    const room = SPEC.rooms[activeRoomIndex];`,
    `    setCompletedRooms((rooms) => rooms.includes(room.roomId) ? rooms : [...rooms, room.roomId]);`,
    `    if (completedRooms.length + 1 >= SPEC.rooms.length) {`,
    `      Meoluna.complete({ engine: 'movement-space', world: SPEC.world.worldName });`,
    `    }`,
    `    setActiveRoomIndex(null);`,
    `  }`,
    `  if (activeRoomIndex !== null) {`,
    `    return <RoomScene room={SPEC.rooms[activeRoomIndex]} onBack={() => setActiveRoomIndex(null)} onComplete={completeActiveRoom} />;`,
    `  }`,
    `  return <Hub completedRooms={completedRooms} onStart={setActiveRoomIndex} />;`,
    `}`,
  ].join("\n");
}
