import type { MovementEngineSpec } from "./movementSpaceTypes";
import { validateMovementEngineSpec } from "./movementSpaceValidator";

export function buildMovementSpaceWorldCode(spec: MovementEngineSpec): string {
  const validation = validateMovementEngineSpec(spec);
  if (!validation.passed) {
    throw new Error(`Invalid movement-space spec: ${validation.violations.join(" | ")}`);
  }

  const dataJson = JSON.stringify(spec, null, 2);

  return [
    `import { useMemo, useState } from 'react';`,
    `import { motion, AnimatePresence } from 'framer-motion';`,
    `import confetti from 'canvas-confetti';`,
    ``,
    `const SPEC = ${dataJson};`,
    ``,
    `function is2D(position) {`,
    `  return typeof position === 'object' && position !== null;`,
    `}`,
    ``,
    `function addPositions(start, moves) {`,
    `  if (is2D(start)) {`,
    `    return moves.reduce((sum, move) => ({ x: sum.x + move.value.x, y: sum.y + move.value.y }), start);`,
    `  }`,
    `  return moves.reduce((sum, move) => sum + move.value, start);`,
    `}`,
    ``,
    `function samePosition(a, b) {`,
    `  if (is2D(a) || is2D(b)) return is2D(a) && is2D(b) && a.x === b.x && a.y === b.y;`,
    `  return a === b;`,
    `}`,
    ``,
    `function positionLabel(position, unitLabel) {`,
    `  if (is2D(position)) return '(' + position.x + ', ' + position.y + ') ' + unitLabel;`,
    `  return position + ' ' + unitLabel;`,
    `}`,
    ``,
    `function axisPercent(value, coordinateSystem) {`,
    `  const pct = ((value - coordinateSystem.min) / (coordinateSystem.max - coordinateSystem.min)) * 100;`,
    `  return Math.max(4, Math.min(96, pct));`,
    `}`,
    ``,
    `function getRoomMeta(roomId) {`,
    `  return SPEC.world.rooms.find((room) => room.id === roomId) || {};`,
    `}`,
    ``,
    `function clampValue(value) {`,
    `  return Math.max(SPEC.coordinateSystem.min, Math.min(SPEC.coordinateSystem.max, value));`,
    `}`,
    ``,
    `function stepStartPosition(room, stepIndex) {`,
    `  return addPositions(room.startPosition, room.moves.slice(0, stepIndex));`,
    `}`,
    ``,
    `function stepTargetPosition(room, stepIndex) {`,
    `  return addPositions(room.startPosition, room.moves.slice(0, stepIndex + 1));`,
    `}`,
    ``,
    `function moveDirectionText(move) {`,
    `  const value = typeof move.value === 'number' ? move.value : move.value.x;`,
    `  if (value < 0) return SPEC.coordinateSystem.negativeDirectionLabel || 'Minus-Richtung';`,
    `  if (value > 0) return SPEC.coordinateSystem.positiveDirectionLabel || 'Plus-Richtung';`,
    `  return 'stehen bleiben';`,
    `}`,
    ``,
    `function valueOf(position) {`,
    `  return typeof position === 'number' ? position : position.x;`,
    `}`,
    ``,
    `function equationText(room, uptoStep) {`,
    `  const moves = room.moves.slice(0, uptoStep + 1).map((move) => valueOf(move.value));`,
    `  if (moves.length === 0) return String(valueOf(room.startPosition));`,
    `  const left = moves.map((value, index) => index === 0 ? String(value) : (value < 0 ? ' + (' + value + ')' : ' + ' + value)).join('');`,
    `  return left + ' = ' + valueOf(addPositions(room.startPosition, room.moves.slice(0, uptoStep + 1)));`,
    `}`,
    ``,
    `function GuidePanel({ room, message }) {`,
    `  return (`,
    `    <div className="rounded-2xl border border-white/10 bg-white/10 p-4 sm:p-5 shadow-2xl backdrop-blur">`,
    `      <div className="flex items-start gap-3">`,
    `        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/15 text-2xl">✦</div>`,
    `        <div>`,
    `          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-white/60">{SPEC.world.guide.name}</p>`,
    `          <p className="mt-1 text-lg font-bold text-white">{message || room.objective}</p>`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function AxisScene({ room, position, selectedPosition, onSelectPosition, stepIndex }) {`,
    `  const coordinateSystem = SPEC.coordinateSystem;`,
    `  const horizontal = coordinateSystem.dimensions !== '1d-vertical';`,
    `  const numericPosition = typeof position === 'number' ? position : position.x;`,
    `  const numericSelected = typeof selectedPosition === 'number' ? selectedPosition : selectedPosition.x;`,
    `  const startOfStep = valueOf(stepStartPosition(room, stepIndex));`,
    `  const currentMove = room.moves[stepIndex];`,
    `  const pathStartPct = axisPercent(Math.min(startOfStep, numericSelected), coordinateSystem);`,
    `  const pathWidthPct = Math.max(1, Math.abs(axisPercent(numericSelected, coordinateSystem) - axisPercent(startOfStep, coordinateSystem)));`,
    `  const markerStyle = horizontal`,
    `    ? { left: axisPercent(numericPosition, coordinateSystem) + '%', top: '50%' }`,
    `    : { left: '50%', bottom: axisPercent(numericPosition, coordinateSystem) + '%' };`,
    `  const selectedStyle = horizontal`,
    `    ? { left: axisPercent(numericSelected, coordinateSystem) + '%', top: '50%' }`,
    `    : { left: '50%', bottom: axisPercent(numericSelected, coordinateSystem) + '%' };`,
    `  function handleTrackClick(event) {`,
    `    const rect = event.currentTarget.getBoundingClientRect();`,
    `    const ratio = horizontal`,
    `      ? (event.clientX - rect.left) / rect.width`,
    `      : 1 - ((event.clientY - rect.top) / rect.height);`,
    `    const value = Math.round(coordinateSystem.min + ratio * (coordinateSystem.max - coordinateSystem.min));`,
    `    onSelectPosition(clampValue(value));`,
    `  }`,
    `  const ticks = [];`,
    `  const span = coordinateSystem.max - coordinateSystem.min;`,
    `  const step = Math.max(1, Math.ceil(span / 8 / 5) * 5);`,
    `  for (let value = Math.ceil(coordinateSystem.min / step) * step; value <= coordinateSystem.max; value += step) ticks.push(value);`,
    `  return (`,
    `    <div onClick={handleTrackClick} className="relative h-[26rem] cursor-crosshair overflow-hidden rounded-3xl border border-white/10 bg-black/30 p-6 shadow-2xl">`,
    `      <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, rgba(125,211,252,0.23), rgba(15,23,42,0.2) 48%, rgba(74,222,128,0.18) 49%, rgba(120,53,15,0.35) 80%)' }} />`,
    `      <div className="absolute inset-x-6 bottom-10 h-28 rounded-b-3xl bg-gradient-to-b from-lime-700/55 via-lime-900/70 to-amber-950/80">`,
    `        <div className="absolute inset-x-0 top-0 h-8 bg-emerald-300/75" />`,
    `      </div>`,
    `      <div className="absolute left-20 top-20 h-10 w-44 rounded-xl bg-white/70" />`,
    `      <div className="absolute left-36 top-28 h-10 w-36 rounded-xl bg-white/60" />`,
    `      <div className="absolute right-28 top-16 h-16 w-16 rotate-12 rounded-xl bg-yellow-300 shadow-[0_0_35px_rgba(250,204,21,0.45)]" />`,
    `      <div className={horizontal ? 'absolute left-12 right-12 top-[58%] h-1 rounded-full bg-white/80' : 'absolute bottom-12 top-12 left-1/2 w-1 rounded-full bg-white/70'} />`,
    `      {horizontal && ticks.map((tick) => (`,
    `        <div key={tick} className="absolute top-[55%] flex -translate-x-1/2 flex-col items-center gap-2 text-sm font-black text-white/75" style={{ left: axisPercent(tick, coordinateSystem) + '%' }}>`,
    `          <div className="h-8 w-1 rounded-full bg-white/80" />`,
    `          <span>{tick}</span>`,
    `        </div>`,
    `      ))}`,
    `      {horizontal && currentMove && (`,
    `        <div className="absolute top-[55%] h-4 rounded-full bg-amber-300/85 shadow-lg shadow-amber-300/30" style={{ left: pathStartPct + '%', width: pathWidthPct + '%' }} />`,
    `      )}`,
    `      <div className="absolute left-12 bottom-6 text-sm font-black text-white/65">{coordinateSystem.negativeDirectionLabel || 'Nach Westen'}</div>`,
    `      <div className="absolute right-12 bottom-6 text-sm font-black text-white/65">{coordinateSystem.positiveDirectionLabel || 'Nach Osten'}</div>`,
    `      <motion.div`,
    `        className="absolute z-30 flex -translate-x-1/2 -translate-y-[88%] flex-col items-center"`,
    `        animate={markerStyle}`,
    `        transition={{ type: 'spring', stiffness: 120, damping: 18 }}`,
    `      >`,
    `        <div className="mb-1 rounded-xl bg-slate-950 px-3 py-1 text-sm font-black text-white shadow-xl">{positionLabel(position, coordinateSystem.unitLabel)}</div>`,
    `        <div className="h-8 w-8 rounded-t-md border-4 border-slate-900 bg-amber-200" />`,
    `        <div className="h-10 w-12 border-4 border-slate-900 bg-green-500" />`,
    `        <div className="-mt-1 flex gap-2"><div className="h-8 w-4 border-4 border-slate-900 bg-blue-600" /><div className="h-8 w-4 border-4 border-slate-900 bg-blue-600" /></div>`,
    `      </motion.div>`,
    `      <motion.div className="absolute z-20 h-14 w-14 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-emerald-300/90 bg-emerald-300/20 shadow-lg shadow-emerald-300/30" animate={selectedStyle} transition={{ type: 'spring', stiffness: 160, damping: 20 }} />`,
    `      <motion.div className="absolute z-20 -translate-x-1/2 -translate-y-[180%] rounded-xl bg-yellow-300 px-4 py-2 text-base font-black text-slate-950 shadow-xl" animate={selectedStyle} transition={{ type: 'spring', stiffness: 160, damping: 20 }}>Ziel: {positionLabel(selectedPosition, coordinateSystem.unitLabel)}</motion.div>`,
    `      <div className="absolute right-5 top-5 rounded-xl bg-white/10 px-3 py-2 text-sm font-semibold text-white/75">Klicke in die Grafik oder ziehe den Marker unten.</div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function RoomScene({ room, onBack, onComplete }) {`,
    `  const roomMeta = getRoomMeta(room.roomId);`,
    `  const [position, setPosition] = useState(room.startPosition);`,
    `  const [stepIndex, setStepIndex] = useState(0);`,
    `  const [selectedPosition, setSelectedPosition] = useState(typeof room.startPosition === 'number' ? room.startPosition : room.startPosition.x);`,
    `  const [feedback, setFeedback] = useState(null);`,
    `  const [solvedEquation, setSolvedEquation] = useState(null);`,
    `  const currentMove = room.moves[stepIndex];`,
    `  const expectedPosition = currentMove ? stepTargetPosition(room, stepIndex) : room.targetPosition;`,
    `  const expectedNumber = valueOf(expectedPosition);`,
    `  const selectedNumber = Number(selectedPosition);`,
    `  const stepStart = valueOf(stepStartPosition(room, stepIndex));`,
    ``,
    `  function completeRoom(message) {`,
    `    setFeedback({ type: 'success', message });`,
    `    Meoluna.reportScore(25, { action: 'movement-room-complete', roomId: room.roomId });`,
    `    Meoluna.completeModule(room.roomId, 25);`,
    `    confetti({ particleCount: 90, spread: 70, origin: { y: 0.65 } });`,
    `    setTimeout(onComplete, 1200);`,
    `  }`,
    ``,
    `  function commitSelectedPosition() {`,
    `    if (!currentMove) return;`,
    `    if (samePosition(selectedNumber, expectedNumber)) {`,
    `      setPosition(expectedNumber);`,
    `      setSelectedPosition(expectedNumber);`,
    `      setSolvedEquation(equationText(room, stepIndex));`,
    `      Meoluna.reportScore(10, { action: 'movement-step-correct', roomId: room.roomId, stepIndex });`,
    `      if (stepIndex + 1 >= room.moves.length) {`,
    `        completeRoom(room.feedback.correct);`,
    `      } else {`,
    `        const nextStep = stepIndex + 1;`,
    `        setStepIndex(nextStep);`,
    `        const nextStart = valueOf(stepStartPosition(room, nextStep));`,
    `        setSelectedPosition(nextStart);`,
    `        setFeedback({ type: 'progress', message: 'Richtig. Jetzt kommt der zweite Weg: ' + room.moves[nextStep].label });`,
    `      }`,
    `      return;`,
    `    }`,
    `    const intendedDirection = Math.sign(expectedNumber - stepStart);`,
    `    const guessedDirection = Math.sign(selectedNumber - stepStart);`,
    `    if (intendedDirection !== guessedDirection) {`,
    `      setFeedback({ type: 'error', message: room.feedback.wrongDirection });`,
    `    } else {`,
    `      setFeedback({ type: 'error', message: room.feedback.wrongDistance });`,
    `    }`,
    `  }`,
    ``,
    `  return (`,
    `    <div className="min-h-screen p-4 text-white sm:p-8" style={{ background: 'linear-gradient(135deg, ' + SPEC.world.visualStyle.palette[0] + ', ' + SPEC.world.visualStyle.palette[1] + ')' }}>`,
    `      <div className="mx-auto flex max-w-6xl flex-col gap-5">`,
    `        <div className="flex items-center justify-between gap-3">`,
    `          <button onClick={onBack} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold text-white/80 hover:bg-white/15">← Karte</button>`,
    `          <div className="rounded-xl bg-white/10 px-4 py-2 text-sm text-white/70">{roomMeta.title || room.roomId}</div>`,
    `        </div>`,
    `        <GuidePanel room={room} message={feedback?.message || (currentMove ? 'Ziehe die Figur: ' + currentMove.label + ' nach ' + moveDirectionText(currentMove) : room.objective)} />`,
    `        <AxisScene room={room} position={position} selectedPosition={selectedNumber} onSelectPosition={setSelectedPosition} stepIndex={stepIndex} />`,
    `        <div className="grid gap-4 lg:grid-cols-[1fr_0.8fr]">`,
    `          <div className="rounded-2xl border border-white/10 bg-white/10 p-5">`,
    `            <p className="text-sm uppercase tracking-[0.18em] text-white/50">Aus der Bewegung wird</p>`,
    `            <h2 className="mt-1 text-2xl font-black">{solvedEquation || 'Setze erst den Zielmarker in der Grafik.'}</h2>`,
    `            <p className="mt-2 text-white/70">{solvedEquation ? room.explanationAfterSuccess : currentMove?.meaning}</p>`,
    `          </div>`,
    `          <div className="rounded-2xl border border-white/10 bg-white/10 p-5">`,
    `            <div className="mb-3 flex items-center justify-between gap-3">`,
    `              <label className="text-sm font-black text-white/75">Zielmarker</label>`,
    `              <span className="rounded-xl bg-slate-950/50 px-3 py-1 text-sm font-black">{positionLabel(selectedNumber, SPEC.coordinateSystem.unitLabel)}</span>`,
    `            </div>`,
    `            <input className="w-full accent-amber-300" type="range" min={SPEC.coordinateSystem.min} max={SPEC.coordinateSystem.max} value={selectedNumber} onChange={(event) => setSelectedPosition(Number(event.target.value))} />`,
    `            <button onClick={commitSelectedPosition} disabled={!currentMove} className="mt-4 w-full rounded-xl bg-amber-300 px-6 py-4 text-lg font-black text-slate-950 shadow-lg shadow-amber-300/20 hover:bg-amber-200 disabled:opacity-40">Marker setzen</button>`,
    `            <p className="mt-3 text-sm text-white/60">Erst in der Grafik oder am Regler setzen, dann prüfen.</p>`,
    `          </div>`,
    `        </div>`,
    `        {feedback?.type === 'error' && (`,
    `          <div className="rounded-2xl border border-red-300/30 bg-red-500/20 p-4 text-red-50">{feedback.message}</div>`,
    `        )}`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `function Hub({ completedRooms, onStart }) {`,
    `  return (`,
    `    <div className="min-h-screen p-4 text-white sm:p-8" style={{ background: 'linear-gradient(135deg, ' + SPEC.world.visualStyle.palette[0] + ', ' + SPEC.world.visualStyle.palette[1] + ')' }}>`,
    `      <div className="mx-auto max-w-6xl">`,
    `        <div className="mb-8 rounded-3xl border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur">`,
    `          <p className="text-sm uppercase tracking-[0.2em] text-white/55">Meoluna Movement Engine</p>`,
    `          <h1 className="mt-2 text-4xl font-black sm:text-6xl">{SPEC.world.worldName}</h1>`,
    `          <p className="mt-3 max-w-3xl text-lg text-white/75">{SPEC.world.setting}</p>`,
    `        </div>`,
    `        <div className="grid gap-4 md:grid-cols-2">`,
    `          {SPEC.rooms.map((room, index) => {`,
    `            const meta = getRoomMeta(room.roomId);`,
    `            const done = completedRooms.includes(room.roomId);`,
    `            return (`,
    `              <button key={room.roomId} onClick={() => onStart(index)} className="group rounded-3xl border border-white/10 bg-white/10 p-5 text-left shadow-xl transition hover:-translate-y-1 hover:bg-white/15">`,
    `                <div className="flex items-start justify-between gap-4">`,
    `                  <div>`,
    `                    <p className="text-sm font-bold uppercase tracking-[0.16em] text-white/50">Raum {index + 1}</p>`,
    `                    <h2 className="mt-1 text-2xl font-black">{meta.title || room.objective}</h2>`,
    `                    <p className="mt-2 text-white/70">{meta.scene || room.objective}</p>`,
    `                  </div>`,
    `                  <div className="rounded-2xl bg-white/10 px-3 py-2 text-sm font-black">{done ? '✓' : '→'}</div>`,
    `                </div>`,
    `              </button>`,
    `            );`,
    `          })}`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export default function App() {`,
    `  const [activeRoomIndex, setActiveRoomIndex] = useState(null);`,
    `  const [completedRooms, setCompletedRooms] = useState([]);`,
    `  function completeActiveRoom() {`,
    `    const room = SPEC.rooms[activeRoomIndex];`,
    `    setCompletedRooms((rooms) => rooms.includes(room.roomId) ? rooms : [...rooms, room.roomId]);`,
    `    if (completedRooms.length + 1 >= SPEC.rooms.length) {`,
    `      Meoluna.complete({ engine: 'movement-space', world: SPEC.world.worldName });`,
    `    }`,
    `    setActiveRoomIndex(null);`,
    `  }`,
    `  if (activeRoomIndex !== null) {`,
    `    return <RoomScene room={SPEC.rooms[activeRoomIndex]} onBack={() => setActiveRoomIndex(null)} onComplete={completeActiveRoom} />;`,
    `  }`,
    `  return <Hub completedRooms={completedRooms} onStart={setActiveRoomIndex} />;`,
    `}`,
  ].join("\n");
}
